# run checks on Markdown writing through proselint script:
# Markdown

language: python
before_install:
  - pip install proselint
  - gem install mdl
notifications: 
  - email: never
script: 
  - mdl README.md 
  - proselint README.md

